config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  root :to => "home#index"
  resources :doctors
  resources :pets
  resources :appointments

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	validates :name_of_pet, :breed, :age, :weight, :date_of_last_visit, presence: true
	validates_length_of :name_of_pet, :breed, :maximum => 35
	has_many :appointments, dependent: :destroy
  	has_many :doctors, through: :appointments
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @users = User.where(:role=> "customer")
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @users = User.where(:role=> "customer")

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
      @users = User.where(:role=> "customer")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name_of_pet, :type_of_pet, :breed, :age, :weight, :date_of_last_visit, :customer_id)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_of_pet %><br>
    <%= f.text_field :name_of_pet, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :type_of_pet %><br>
    <%= f.select :type_of_pet, options_for_select([ "dog", "cat", "bird" ]), class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_area :breed, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :date_of_last_visit %><br>
    <%= f.text_field :date_of_last_visit, class: 'datepicker form-control' %>
  </div>
  <div class="field">
    <%= f.label :customer_id, "Customer Name" %><br>
    <%= f.select :customer_id, @users.collect {|p| [ p.username,p.id ] } %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing Pets</h1>

<table class= "table table-bordered">
  <thead>
    <tr>
      <th>Name of pet</th>
      <th>Type of pet</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Date of last visit</th>
      <th>Customer</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name_of_pet %></td>
        <td><%= pet.type_of_pet %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= pet.date_of_last_visit %></td>
        <td><%= pet.customer_id %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p>
  <strong>Name of pet:</strong>
  <%= @pet.name_of_pet %>
</p>

<p>
  <strong>Type of pet:</strong>
  <%= @pet.type_of_pet %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.weight %>
</p>

<p>
  <strong>Date of last visit:</strong>
  <%= @pet.date_of_last_visit %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @pet.customer_id %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>