config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  root :to => "home#index"
  resources :doctors
  resources :pets
  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :pet
  validates :date_of_visit, :pet_name, :customer_id, :reason_for_visit,  presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
    @users = User.where(:role=> "customer")
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @users = User.where(:role=> "customer")
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_appointment
      @appointment = Appointment.find(params[:id])
      @users = User.where(:role=> "customer")
    end

    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :pet_name, :customer_id, :requires_reminder_of_appointment, :reason_for_visit, :doctor_id, :pet_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.text_field :date_of_visit, :class=> 'dateofvisit form-control' %>
  </div>
  <div class="field">
    <%= f.label :pet_name %><br>
    <%= f.select :pet_name,  options_for_select([ "dog", "cat", "bird" ]) %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.select :customer_id, @users.collect {|p| [ p.username, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :requires_reminder_of_appointment %><br>
    <%= f.text_field :requires_reminder_of_appointment, :class=> 'requires_reminder_of_appointment form-control' %>
  </div>
  <div class="field">
    <%= f.label :reason_for_visit %><br>
    <%= f.text_area :reason_for_visit , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :dector_id %><br>
     <%= f.select :doctor_id, Doctor.all.collect {|p| [ p.name, p.id ] }, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :pet_id, "Pet Name" %><br>
    <%= f.select :pet_id, Pet.all.collect {|p| [p.name_of_pet,  p.id ] }, class: 'form-control' %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing Appointments</h1>

<table class= "table table-bordered">
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Pet</th>
      <th>Requires reminder of appointment</th>
      <th>Reason for visit</th>
      <th>Doctor</th>
      <th>Pet Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.pet_name %></td>
        <td><%= appointment.requires_reminder_of_appointment %></td>
        <td><%= appointment.reason_for_visit %></td>
        <td><%= appointment.doctor.try(:name)   %></td>
        <td><%= appointment.pet.try(:name_of_pet) %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet %>
</p>

<p>
  <strong>Requires reminder of appointment:</strong>
  <%= @appointment.requires_reminder_of_appointment %>
</p>

<p>
  <strong>Reason for visit:</strong>
  <%= @appointment.reason_for_visit %>
</p>


<p>
  <strong>Pet:</strong>
  <%= @appointment.pet_id %>
</p>
<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.try(:name) %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>